root: ./

redirects:
  out-of-band: ./guides/using-the-desktop-app
  desktop-welcome: ./guides/using-the-desktop-app
  connect-mac: ./guides/control-your-computer-remotely-mac-to-mac
  connect-windows: ./guides/using-the-desktop-app/peer-to-peer-connections
  connect-rpi: ./guides/using-the-desktop-app/peer-to-peer-connections
  connect-linux: ./guides/using-the-desktop-app/peer-to-peer-connections
  minecraft: ./guides/hosting-a-minecraft-server
